ALTER TABLE recipes DROP COLUMN IF EXISTS title;
ALTER TABLE recipes DROP COLUMN IF EXISTS ingredients;
ALTER TABLE recipes DROP COLUMN IF EXISTS instructions;
ALTER TABLE recipes DROP COLUMN IF EXISTS total_time;
ALTER TABLE recipes DROP COLUMN IF EXISTS servings;
ALTER TABLE recipes DROP COLUMN IF EXISTS course_type;
