ALTER TABLE recipes ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE recipes ADD COLUMN ingredients TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE recipes ADD COLUMN instructions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE recipes ADD COLUMN total_time INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN servings INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN course_type TEXT NOT NULL DEFAULT '';
